<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * categorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class categorieRepository extends EntityRepository
{
    public function getAll($eleve, $cat)
    {
        $query = $this->createQueryBuilder('c');
        $query
            ->join('AppBundle:validation', 'succes', 'WITH', 'succes.eleve = :student')
            ->addSelect('succes')
            ->where('c.id = :categorie')
            ->setParameter('categorie', $cat)
            ->setParameter('student', $eleve);
        return $query
            ->getQuery()
            ->getResult();
    }
}
