<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * classeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class classeRepository extends EntityRepository
{
    public function getName($id) {
        $query = $this->_em->createQuery('SELECT x.nom FROM AppBundle:classe x WHERE x.id = :id');
        $query->setParameters([
            'id' => $id
        ]);
        return $query
            ->getResult();
    }
    public function getNom($id) {
        $query = $this->_em->createQueryBuilder()
            ->select('c.nom)')
            ->from($this->_entityName, 'c')
            ->where('c.id = :id')
            ->setParameter('id', $id);
        return $query
            ->getQuery()
            ->getResult();
    }
}
