<?php

namespace AppBundle\Repository;
use Doctrine\ORM\EntityRepository;

/**
 * validationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class validationRepository extends EntityRepository
{
    public function getValidDates($eleve, $cat)
    {
        $query = $this->_em->createQuery('SELECT v FROM AppBundle:validation v JOIN v.competence c WITH c.categorie = :categorie WHERE v.eleve = :student');
        $query->setParameters([
            'categorie' => $cat,
            'student' => $eleve
        ]);
        return $query
            ->getResult();
    }
    public function getReport($eleve, $cat)
    {
    /* Attention à bien définir les relations entre les entités avant de construire les requêtes! */
    $query = $this->createQueryBuilder('v');
    $query
        ->join('v.competence', 'c', 'WITH', 'c.categorie = :categorie')
        ->addSelect('c')
        ->where('v.eleve = :student')
        ->setParameter('categorie', $cat)
        ->setParameter('student', $eleve);
    return $query
        ->getQuery()
        ->getResult();
    }

}
